services:
  skill-manager:
    image: ukpsquare/skill-manager:latest
    build:
      context: .
      target: build
    command: uvicorn skill_manager.main:app --reload --host 0.0.0.0 --port 8000 --log-config logging.conf
    networks:
    - skill-manager
    ports:
    - 8000:8000
    expose:
    - 8000
    env_file:
    - .local.env
    environment:
      API_PREFIX: ""
      WEB_CONCURRENCY: "1"
      KEYCLOAK_BASE_URL: ""
      MODEL_API_URL: ""
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      VERIFY_ISSUER: "0"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SQUARE_PRIVATE_KEY_FILE: /app/private_key.pem
    depends_on:
    - mongodb
    - redis
    volumes:
      - ./skill_manager:/app/skill_manager
      - ./private_key.pem:/app/private_key.pem  
  mongodb:
    image: mongo:5.0.4
    restart: always
    volumes:
    - mongo-data:/data/db
    networks:
    - mongodb
    expose:
    - 27017
    ports:
    - 27017:27017
    env_file:
    - .local.env
  redis:
    image: redis:latest
    networks:
    - redis
    ports:
    - 6379:6379
    env_file:
    - .local.env
    command:
    - redis-server
    - --requirepass ${REDIS_PASSWORD}

volumes:
  mongo-data:
networks: 
  skill-manager:
    name: skill_network
    external: true
  mongodb:
    name: skill_network
  redis:
    name: skill_network
